name: Node.js CI for aio-metrics-client

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/aio-metrics-client/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/aio-metrics-client/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd 'packages/aio-metrics-client/'
        npm i --package-lock --package-lock-only
        npm cit
        npm test
    - name: upload coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        name: ${{ runner.os }} node.js ${{ matrix.node-version }}
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
