name: Npm Publish for ab-app-secrets-uploader
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'packages/ab-app-secrets-uploader/package.json'
jobs:
  publish:
    if: github.repository_owner == 'adobe'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: npm install, test, and publish
        run: |
          cd 'packages/ab-app-secrets-uploader/'
          npm install
          npm test
      - uses: JS-DevTools/npm-publish@v4
        with:
          package: packages/ab-app-secrets-uploader/package.json
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: 'public'
