name: Npm Publish for aio-app-builder-repos
on:
  workflow_dispatch:
  push:
    branches:
      - master # Change this if not your default branch
    paths:
      - 'packages/aio-app-builder-repos/package.json'
jobs:
  publish:
    if: github.repository_owner == 'adobe'
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: npm install, test, and publish
        run: |
          cd 'packages/aio-app-builder-repos/'
          npm install
          npm test
      - uses: JS-DevTools/npm-publish@v4
        with:
          package: packages/aio-app-builder-repos/package.json
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          strategy: all
          provenance: true
          access: 'public'
